// <auto-generated />
using System;
using ChessCrm.MigrationTool.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChessCrm.MigrationTool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("GoogleSheetRowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("google_sheet_row_index");

                    b.Property<string>("GoogleSpreadsheetId")
                        .HasColumnType("text")
                        .HasColumnName("google_spreadsheet_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<string>("SyncHash")
                        .HasColumnType("text")
                        .HasColumnName("sync_hash");

                    b.Property<string>("TeacherComment")
                        .HasColumnType("text")
                        .HasColumnName("teacher_comment");

                    b.Property<string>("Topic")
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attendance");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_attendance_client_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_attendance_group_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_attendance_subscription_id");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_data");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("GoogleSheetRowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("google_sheet_row_index");

                    b.Property<string>("GoogleSpreadsheetId")
                        .HasColumnType("text")
                        .HasColumnName("google_spreadsheet_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Parent1Name")
                        .HasColumnType("text")
                        .HasColumnName("parent1_name");

                    b.Property<string>("Parent1Phone")
                        .HasColumnType("text")
                        .HasColumnName("parent1_phone");

                    b.Property<string>("Parent2Name")
                        .HasColumnType("text")
                        .HasColumnName("parent2_name");

                    b.Property<string>("Parent2Phone")
                        .HasColumnType("text")
                        .HasColumnName("parent2_phone");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SyncHash")
                        .HasColumnType("text")
                        .HasColumnName("sync_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachName")
                        .HasColumnType("text")
                        .HasColumnName("coach_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<int?>("GoogleSheetRowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("google_sheet_row_index");

                    b.Property<string>("GoogleSpreadsheetId")
                        .HasColumnType("text")
                        .HasColumnName("google_spreadsheet_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer")
                        .HasColumnName("max_students");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<string>("SyncHash")
                        .HasColumnType("text")
                        .HasColumnName("sync_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.GroupStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("GoogleSheetRowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("google_sheet_row_index");

                    b.Property<string>("GoogleSpreadsheetId")
                        .HasColumnType("text")
                        .HasColumnName("google_spreadsheet_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("SyncHash")
                        .HasColumnType("text")
                        .HasColumnName("sync_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_group_students");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_group_students_client_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_students_group_id");

                    b.ToTable("group_students", (string)null);
                });

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("CardLastDigits")
                        .HasColumnType("text")
                        .HasColumnName("card_last_digits");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("GoogleSheetRowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("google_sheet_row_index");

                    b.Property<string>("GoogleSpreadsheetId")
                        .HasColumnType("text")
                        .HasColumnName("google_spreadsheet_id");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refunded");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_name");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<string>("SyncHash")
                        .HasColumnType("text")
                        .HasColumnName("sync_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_payments_client_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_payments_subscription_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("GoogleSheetRowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("google_sheet_row_index");

                    b.Property<string>("GoogleSpreadsheetId")
                        .HasColumnType("text")
                        .HasColumnName("google_spreadsheet_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<int>("LessonsLeft")
                        .HasColumnType("integer")
                        .HasColumnName("lessons_left");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("SyncHash")
                        .HasColumnType("text")
                        .HasColumnName("sync_hash");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("integer")
                        .HasColumnName("total_lessons");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_subscriptions_client_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.Attendance", b =>
                {
                    b.HasOne("ChessCrm.MigrationTool.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_clients_client_id");

                    b.HasOne("ChessCrm.MigrationTool.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_groups_group_id");

                    b.HasOne("ChessCrm.MigrationTool.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .HasConstraintName("fk_attendance_subscriptions_subscription_id");

                    b.Navigation("Client");

                    b.Navigation("Group");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.GroupStudent", b =>
                {
                    b.HasOne("ChessCrm.MigrationTool.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_students_clients_client_id");

                    b.HasOne("ChessCrm.MigrationTool.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_students_groups_group_id");

                    b.Navigation("Client");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.Payment", b =>
                {
                    b.HasOne("ChessCrm.MigrationTool.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .HasConstraintName("fk_payments_clients_client_id");

                    b.HasOne("ChessCrm.MigrationTool.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .HasConstraintName("fk_payments_subscriptions_subscription_id");

                    b.Navigation("Client");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ChessCrm.MigrationTool.Entities.Subscription", b =>
                {
                    b.HasOne("ChessCrm.MigrationTool.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_clients_client_id");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
